---
- name: Collect vm info
  hosts: all
  tasks:
    - setup:

- name: Initialize
  hosts: all
  roles:
    - init
  become: yes
  gather_facts: no

- name: Minecraft
  hosts: minecraft
  roles:
    - minecraft
  become: yes
  gather_facts: no
