---
- name: create minecraft user
  user:
    name: minecraft
    shell: /bin/bash
    home: /home/minecraft

- apt:
    name:
      - acl # for ansible to become minecraft user
      - nano # personal purposes
      - openjdk-19-jre-headless
      - tmux
    state: latest

- include_tasks: iptables.yaml # Oracle Cloud

- file:
    path: "{{ item }}"
    state: directory
    owner: minecraft
    group: minecraft
  loop:
     - /home/minecraft/{{server_name}}
     - /home/minecraft/{{server_name}}/ansible
     - /home/minecraft/{{server_name}}/config
     - /home/minecraft/{{server_name}}/plugins

- name: download papermc
  get_url:
    url: https://papermc.io/api/v2/projects/paper/versions/{{version}}/builds/{{build}}/downloads/paper-{{version}}-{{build}}.jar
    dest: /home/minecraft/{{server_name}}/server.jar
    owner: minecraft
    group: minecraft
    mode: 0700

- name: eula.txt
  template:
    src: eula.txt
    dest: /home/minecraft/{{server_name}}/eula.txt
    owner: minecraft
    group: minecraft

- name: server-icon.png
  copy:
    src: server-icon.png
    dest: /home/minecraft/{{server_name}}/server-icon.png
    owner: minecraft
    group: minecraft
    mode: 0775

- name: server.properties
  template:
    src: server.properties
    dest: /home/minecraft/{{server_name}}/ansible/server.properties
    owner: minecraft
    group: minecraft
  notify:
    - change paper configs
    - restart minecraft

- template:
    src: "{{ item }}"
    dest: /home/minecraft/{{server_name}}/ansible/{{ item }}
    owner: minecraft
    group: minecraft
  loop:
    - paper-global.yml
    - paper-world-defaults.yml
  notify:
    - change paper configs
    - restart minecraft

- include_tasks: plugins.yaml # OpeNLogin

- template:
    src: mc.sh.j2
    dest: /usr/local/bin/mc
    mode: 0755

- meta: flush_handlers

- name: check minecraft status
  command: pgrep -x -f 'tmux new-session -d -s minecraft cd /home/minecraft/{{server_name}} && java -Xms{{mc_gb_min}}G -Xmx{{mc_gb_max}}G -jar server.jar nogui'
  register: minecraft_pid
  changed_when: false
  check_mode: false
  failed_when: false

- name: start minecraft
  become: true
  become_user: minecraft
  become_method: sudo
  shell: mc start
  when: minecraft_pid.stdout == ""
